os: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "14"

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn
  - node scripts/build-native.js

build_script:
  - yarn run build
  - node scripts/prepackage-plugins.js
  - node scripts/build-windows.js

artifacts:
  - path: 'dist\*.exe'

cache:
  - node_modules
  - "*\\node_modules"
  - "%USERPROFILE%\\.electron"
  - "%LOCALAPPDATA%\\Yarn"
