hotkeys:
  new-window:
    - '⌘-N'
  toggle-window:
    - 'Ctrl+Space'
  toggle-fullscreen:
    - 'Ctrl+⌘+F'
  close-tab:
    - '⌘-W'
  reopen-tab:
    - '⌘-Shift-T'
  toggle-last-tab: []
  rename-tab:
    - '⌘-R'
  next-tab:
    - 'Ctrl-Tab'
  previous-tab:
    - 'Ctrl-Shift-Tab'
  move-tab-left:
    - '⌘-Shift-Left'
  move-tab-right:
    - '⌘-Shift-Right'
  tab-1:
    - '⌘-1'
  tab-2:
    - '⌘-2'
  tab-3:
    - '⌘-3'
  tab-4:
    - '⌘-4'
  tab-5:
    - '⌘-5'
  tab-6:
    - '⌘-6'
  tab-7:
    - '⌘-7'
  tab-8:
    - '⌘-8'
  tab-9:
    - '⌘-9'
  tab-10:
    - '⌘-0'
  split-right:
    - '⌘-Shift-D'
  split-bottom:
    - '⌘-D'
  split-left: []
  split-top: []
  pane-nav-right:
    - '⌘-⌥-Right'
  pane-nav-down:
    - '⌘-⌥-Down'
  pane-nav-up:
    - '⌘-⌥-Up'
  pane-nav-left:
    - '⌘-⌥-Left'
  pane-maximize:
    - '⌘-⌥-Enter'
  close-pane:
    - '⌘-Shift-W'
pluginBlacklist: ['ssh']
