appearance:
  dock: off
  dockScreen: current
  dockFill: 0.5
  tabsLocation: top
  cycleTabs: true
  theme: Standard
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1.0
  vibrancy: true
  vibrancyType: 'blur'
enableAnalytics: true
enableWelcomeTab: true
electronFlags:
  - ['force_discrete_gpu', '0']
enableAutomaticUpdates: true
