appearance:
  dock: off
  dockScreen: current
  dockFill: 50
  tabsLocation: top
  cycleTabs: true
  theme: Standard
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1.0
  vibrancy: false
  vibrancyType: 'blur'
enableAnalytics: true
