hotkeys:
  new-window:
    - '⌘-N'
  toggle-window:
    - 'Ctrl+Space'
  toggle-fullscreen:
    - 'Ctrl+⌘+F'
  close-tab:
    - '⌘-W'
  toggle-last-tab: []
  next-tab:
    - 'Ctrl-Tab'
  previous-tab:
    - 'Ctrl-Shift-Tab'
  tab-1:
    - '⌘-1'
  tab-2:
    - '⌘-2'
  tab-3:
    - '⌘-3'
  tab-4:
    - '⌘-4'
  tab-5:
    - '⌘-5'
  tab-6:
    - '⌘-6'
  tab-7:
    - '⌘-7'
  tab-8:
    - '⌘-8'
  tab-9:
    - '⌘-9'
  tab-10:
    - '⌘-0'
pluginBlacklist: ['ssh']
