hotkeys:
  toggle-fullscreen:
    - 'Ctrl+⌘+F'
  close-tab:
    - '⌘-W'
  reopen-tab:
    - '⌘-Shift-T'
  toggle-last-tab: []
  rename-tab:
    - '⌘-R'
  next-tab:
    - 'Ctrl-Tab'
  previous-tab:
    - 'Ctrl-Shift-Tab'
  move-tab-left:
    - '⌘-Shift-Left'
  move-tab-right:
    - '⌘-Shift-Right'
  rearrange-panes:
    - 'Ctrl-Shift'
  tab-1:
    - '⌘-1'
  tab-2:
    - '⌘-2'
  tab-3:
    - '⌘-3'
  tab-4:
    - '⌘-4'
  tab-5:
    - '⌘-5'
  tab-6:
    - '⌘-6'
  tab-7:
    - '⌘-7'
  tab-8:
    - '⌘-8'
  tab-9:
    - '⌘-9'
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - '⌘-Shift-.'
  combine-tabs:
    - '⌘-Shift-,'
  split-right:
    - '⌘-Shift-D'
  split-bottom:
    - '⌘-D'
  split-left: []
  split-top: []
  pane-nav-right:
    - '⌘-⌥-Right'
  pane-nav-down:
    - '⌘-⌥-Down'
  pane-nav-up:
    - '⌘-⌥-Up'
  pane-nav-left:
    - '⌘-⌥-Left'
  pane-nav-previous:
    - '⌘-⌥-['
  pane-nav-next:
    - '⌘-⌥-]'
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - '⌘-⌥-Enter'
  close-pane:
    - '⌘-Shift-W'
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - '⌘-E'
  switch-profile:
    - '⌘-Shift-E'
  command-selector:
    - '⌘-Shift-P'
  search-up: []
  search-down: []
